### ISSUE TITLE
Unterminated Promise

### ISSUE THREAD

**Issue by nerdDan** [BiteBit/koa-oai-router#45]
An error occurred while I was testing a REST server with `jest` and `supertest`. It seems a __stuck__ `Promise` in `koa-oai-router` was detected.

```
Jest has detected the following 3 open handles potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at dns.js:338:23


  ●  PROMISE



          at Promise.then (<anonymous>)
      at OAIRouter.routes (node_modules/koa-oai-router/lib/router.js:100:40)
      at Object.<anonymous> (src/index.ts:141:16)
      at Object.<anonymous> (test/app.test.ts:3:1)


  ●  PROMISE



          at Promise.then (<anonymous>)
          at Promise.catch (<anonymous>)
      at OAIRouter.routes (node_modules/koa-oai-router/lib/router.js:114:17)
      at Object.<anonymous> (src/index.ts:141:16)
      at Object.<anonymous> (test/app.test.ts:3:1)
```

**Comment by BiteBit** [comment]
Sorry for the incomplete docs.
The api parser of router is asynchronous. Router has two events **ready**, **error**. 
* **ready** means the api doc is parsed and the routes are mounted.
* **error** means the api doc parse error or any other errors.

Before router ready, you should't use it.
You can refer to my test code.
https://github.com/BiteBit/koa-oai-router/blob/6f11e25288ec3e69f279fcdb7abce57876bb8b6e/test/helpers/index.js#L12-L38

**Comment by nerdDan** [comment]
Thank you for replying.

I have tried the method you gave (with a little bit difference). And it did not work for me.

```typescript
// app.ts
// ...
const router = new Router({
  apiDoc: path.join(__dirname, "api"),
  apiExplorerVisible: true
});
router.mount(middleware, path.join(__dirname, "controllers"));
app.use(router.routes());

validate(app);

export { app, router };
```

```typescript
// app.spec.ts
import request from "supertest";

import { app, router } from "../src";

const status = new Promise((resolve, reject) => {
  router.on("ready", resolve);
  router.on("error", error => {
    reject(error);
  });
});

describe("routes: misc", async () => {
  await status;
// ...
```

Now I get this.

```
Jest has detected the following 4 open handles potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at dns.js:338:23


  ●  PROMISE



          at Promise.then (<anonymous>)
          at Promise.catch (<anonymous>)
      at OAIRouter.routes (node_modules/koa-oai-router/lib/router.js:114:17)
      at Object.<anonymous> (src/index.ts:143:16)
      at Object.<anonymous> (test/app.spec.ts:3:1)


  ●  PROMISE

      11 | });
      12 | 
    > 13 | const status = new Promise((resolve, reject) => {
         |                ^
      14 |   router.on("ready", resolve);
      15 |   router.on("error", error => {
      16 |     reject(error);

      at Object.<anonymous> (test/app.spec.ts:13:16)
```

**Comment by nerdDan** [comment]
The website runs properly without errors. I am just ignoring this error.
